### ISSUE TITLE
not working!

### ISSUE THREAD

**Issue by rishavbhurtel** [syohex/java-simple-mine-sweeper#1]
when i try to run i get the layout but the board is not loading it only shows border and inside it number 40

**Comment by syohex** [comment]
![mine](https://user-images.githubusercontent.com/554281/79124294-f54a9300-7dd6-11ea-80e2-0b50350318a6.gif)

```shell
javac Mines.java
java Mine
```

I suppose it works. However this is very old my product, I don't remember anything.
